version: 2.1

executors:
  rust-executor:
    docker:
      - image: rust:latest

jobs:
  check-fmt:
    executor: rust-executor
    steps:
      - checkout
      - run:
          name: install rustfmt
          command: rustup component add rustfmt
      - run:
          name: check formatting
          command: cargo fmt -- --check
  build-native:
    executor: rust-executor
    steps:
      - checkout
      - run:
          name: build salva2d
          command: cargo build --verbose -p salva2d;
      - run:
          name: build salva2d (all features)
          command: cargo build --verbose -p salva2d --all-features;
      - run:
          name: build salva3d
          command: cargo build --verbose -p salva3d;
      - run:
          name: build salva3d (all features)
          command: cargo build --verbose -p salva3d --all-features;
#      - run:
#          name: build examples-2d
#          command: cargo build -j 1 --verbose -p examples2d;
#      - run:
#          name: build examples-3d
#          command: cargo build -j 1 --verbose -p examples3d;
      - run:
          name: test salva2d
          command: cargo test --verbose -p salva2d;
      - run:
          name: test salva3d
          command: cargo test --verbose -p salva3d;
  build-wasm:
    executor: rust-executor
    steps:
      - checkout
      - run:
          name: install cargo-web
          command: cargo install -f cargo-web;
      - run:
          name: build salva2d
          command: cd build/salva2d && cargo build --verbose --features wasm-bindgen --target wasm32-unknown-unknown;
      - run:
          name: build salva3d
          command: cd build/salva3d && cargo build --verbose --features wasm-bindgen --target wasm32-unknown-unknown;
#      - run:
#          name: build examples-2d
#          command: cd examples2d && cargo web build --verbose --target wasm32-unknown-unknown;
#      - run:
#          name: build examples-3d
#          command: cd examples3d && cargo web build --verbose --target wasm32-unknown-unknown;


workflows:
  version: 2
  build:
    jobs:
      - check-fmt
      - build-native:
          requires:
            - check-fmt
      - build-wasm:
          requires:
            - check-fmt
